remote_theme: fongandrew/hydeout
paginate: 10
title: Clemson AI Club
description: For Students Passionate about ML/AI

permalink: /:categories/:title:output_ext
markdown: kramdown

disqus:
  shortname: https-clemson-ai-github-io
