remote_theme: fongandrew/hydeout
paginate: 10
title: Clemson AI Club
description: work in progress website for Clemson AI Club

permalink: /:categories/:title:output_ext

disqus:
  shortname: https-clemson-ai-github-io
